# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: 1103_NAFNet_code_uncertainty_RealBlurR
model_type: ImageRestorationModel
scale: 1
num_gpu: 8
manual_seed: 10

datasets:
  train:
    name: gopro-train
    type: PairedImageDataset
    dataroot_gt: ./datasets/RealBlur-R/train/sharp_crops.lmdb
    dataroot_lq: ./datasets/RealBlur-R/train/blur_crops.lmdb

    filename_tmpl: '{}'
    io_backend:
      type: lmdb # lmdb
    
    gt_size: 256 # 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8 
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: gopro-test
    type: PairedImageDataset
    dataroot_gt: ./datasets/RealBlur-R/test/target
    dataroot_lq: ./datasets/RealBlur-R/test/input
    io_backend:
      type: disk # (folder), lmdb


network_g:
  type: NAFNet_code_uncertainty_Local
  width: 64
  enc_blk_nums: [1, 1, 1, 28]
  middle_blk_num: 1
  dec_blk_nums: [1, 1, 1, 1]

# path
path:
  pretrain_network_g: ./experiments/pretrained_models/kernel_extract_uncertainty_480000.pth # ./experiments/1016_NAFNet_code_uncertainty/models/net_g_170000.pth 
  strict_load_g: false # true false
  resume_state: ~


# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-4 # 1e-3
    weight_decay: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 400000
    eta_min: !!float 1e-7

  total_iter: 1600000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 2e4 # 2e4
  save_img: false # false


  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
