# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: 1208_NAFNet_code_uncertainty_GoPro
model_type: ImageRestorationModel
scale: 1
num_gpu: 1 # 8
manual_seed: 10

datasets:
  train:
    name: gopro-train
    type: PairedImageDataset
    dataroot_gt: D:/Fang/dataset/Deblur/GoPro/train/target # /home/fangzhenxuan/study/code/NAFNet_motionkernel/datasets/GoPro/train/sharp_crops.lmdb # ./datasets/GoPro_BHJR/train/sharp_crops.lmdb
    dataroot_lq: D:/Fang/dataset/Deblur/GoPro/train/input # /home/fangzhenxuan/study/code/NAFNet_motionkernel/datasets/GoPro/train/blur_crops.lmdb #./datasets/GoPro_BHJR/train/blur_crops.lmdb

    filename_tmpl: '{}'
    io_backend:
      type: disk # lmdb
    
    gt_size: 256 # 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 1
    batch_size_per_gpu: 1 # 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: gopro-test
    type: PairedImageDataset
    dataroot_gt: D:/Fang/dataset/Deblur/GoPro/test/target # /home/fangzhenxuan/study/code/CVPR23_Deblur/NAFNet_kernel/datasets/GoPro_BHJR/test/target
    dataroot_lq: D:/Fang/dataset/Deblur/GoPro/test/input # /home/fangzhenxuan/study/code/CVPR23_Deblur/NAFNet_kernel/datasets/GoPro_BHJR/test/input
    io_backend:
      type: disk # (folder), lmdb


network_g:
  type: NAFNet_code_uncertainty_Local
  width: 64
  enc_blk_nums: [1, 1, 1, 28]
  middle_blk_num: 1
  dec_blk_nums: [1, 1, 1, 1]

# path
path:
  pretrain_network_g: ../experiments/pretrained_models_1206/kernel_extract_uncertainty_480000.pth # ./experiments/1016_NAFNet_code_uncertainty/models/net_g_170000.pth
  strict_load_g: false # true false
  resume_state: ~


# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3 # 1e-3 1e-4                  注意后期 -4 !!!!!!!!!!!
    weight_decay: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 800000
    eta_min: !!float 1e-7

  total_iter: 800000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean

  reblur_opt:
    type: L1Loss
    loss_weight: 0.01
    reduction: mean

# validation settings
val:
  val_freq: !!float 4e4 # 2e4
  save_img: false # false


  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 4e4   # 1e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
